demo/demo/urls.py
# from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

demo/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
# add this to let django differentiate which url to select if there is
# conflict while using multiple apps
urlpatterns = [
    # path('', views.index, name='index'),
    # path('<int:question_id>/', views.detail, name='detail'),
    # path('<int:question_id>/results/', views.results, name='results'),
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]
# using generic views to remove redundancy

# https://stackoverflow.com/questions/39574813/error-loading-mysqldb-module-no-module-named-mysqldb

demo/polls/models.py
import datetime
# from secrets import choice
from django.utils import timezone
from django.db import models
from django.contrib import admin
# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    # Question.objects.all() does not produce string output

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Published recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        # return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        # checking if pub_date is > than one day previous date time


class Choice(models.Model):
    # foreign key proivides Many to one mapping
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
# https://docs.djangoproject.com/en/4.0/ref/models/fields/#django.db.models.ForeignKey
# above link to better understand foreignkey parameters
# cascade if parent is deleted it will affect the child too in case of restrict it will restrict parent from deleting if inherited
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


# It’s important to add __str__() methods to your models, not only for your
# own convenience when dealing with the interactive prompt, but also because
# objects’ representations are used throughout Django’s automatically-generated admin.


# python shell tutorial:
# https://docs.djangoproject.com/en/4.0/intro/tutorial02/

demo/polls/views.py
from django.utils import timezone
from django.views import generic
from urllib import response
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
# Create your views here.
from django.urls import reverse
from .models import Question, Choice
from django.template import loader


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    {  # in order by - sign gives desc order and no sign give asc

        # output = ', '.join([q.question_text for q in latest_question_list])
        # return HttpResponse(output)
        # There’s a problem here, though: the page’s design is hard-coded
        # in the view. If you want to change the way the page looks,
        # you’ll have to edit this Python code. So let’s use Django’s
        # template system
    }
    context = {'latest_question_list': latest_question_list, }
    {
        # template = loader.get_template('polls/index.html')
        # return HttpResponse(template.render(context, request))

        # render is an easy way
        # both can be used template as well as render
    }
    return render(request, 'polls/index.html', context)
    {
        # It’s a very common idiom to load a template, fill a
        # context and return an HttpResponse object with the
        # result of the rendered template
    }


def detail(request, question_id):

    # raising a 404 error
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    # return HttpResponse("You're looking at question %s." % question_id)

    # shortcut
    question1 = get_object_or_404(Question, pk=question_id)

    return render(request, 'polls/detail.html', {'question': question1})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))
        # As the Python comment above points out, you should always return an
        #  HttpResponseRedirect after successfully dealing with
        # POST data.


{  # In our poll application, we’ll have the following four views:

    # Question “detail” page – displays a question text, with no results but with a form to vote.
    # Question “results” page – displays results for a particular question.
    # Question “index” page – displays the latest few questions.
    # Vote action – handles voting for a particular choice in a particular question.
}


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        # return Question.objects.order_by('-pub_date')[:5]
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
        # lte less than or equal to


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

demo/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- <h1>{{ question.question_text }}</h1> -->

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>




</body>
</html>
<!-- no idea how Choice is imported along
    with Question class may be creating a fk makes this kind of relation(lazy relation) -->

demo/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%if latest_question_list%}
    <ul>
        {%for question in latest_question_list%}
        <li>
            <!-- <a href="/polls/{{question.id}}/"> -->
                <!-- removing hardcoded urls -->
                <!-- from polls.url we can directly use its url -->
                <a href="{%url 'polls:detail' question.id%}">
                    <!-- specifying polls in front helps in resolving conflict 
                    if similar name url exists -->
            {{question.question_text}}
        </a></li>
        {%endfor%}
    </ul>
    {%else%}
    <p>No polls available</p>
    {%endif%}
</body>
</html>

demo/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>